### ISSUE TITLE
onMute event not configurable

### ISSUE THREAD

**Issue by sudojunior** [Sven65/Sledgehammer#4]
![image](https://cloud.githubusercontent.com/assets/8607699/20041843/3cf0526e-a467-11e6-91d0-db95079d01e6.png)
`onMute` isn't an event that can be configurable yet.

Confirmed by Mackan.
![image](https://cloud.githubusercontent.com/assets/8607699/20041862/84578aa0-a467-11e6-8121-ccff0f88105a.png)

**Comment by Sven65** [comment]
Fixed.
