### ISSUE TITLE
Transfer database commands to rethinkdbdash

### ISSUE THREAD

**Issue by sudojunior** [Sven65/Sledgehammer#8]
**TODO**

- Remove Connection in .run() prototype.
- Init connection upon loading the driver.
- Remove all connections related to database queries and parse a connection pool.

https://github.com/neumino/rethinkdbdash

**Comment by PlayTheFallen** [comment]
- Remove Connection in `.run()` prototype.
- Init connection upon loading the driver.
- Remove all connections related to database queries and parse a connection pool.

https://github.com/neumino/rethinkdbdash
